/* Kagura manual update helper */
(() => {
  'use strict';
  const CURRENT = (typeof APP_VERSION !== 'undefined' && APP_VERSION) || (typeof MODULE_VERSION !== 'undefined' && MODULE_VERSION) || '3.0.28';
  const BASE = 'https://raw.githubusercontent.com/kagura00101001-cyber/Utopia-update/main/';
  const MANIFEST = BASE + 'latest.json';
  const INSTALL = BASE + 'Ozon_ChatGPT.user.js';

  function cmp(a,b){const A=String(a).split('.').map(Number),B=String(b).split('.').map(Number);for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0;if(x>y)return 1;if(x<y)return-1;}return 0;}
  function get(url){return new Promise((ok,no)=>GM_xmlhttpRequest({method:'GET',url:url+(url.includes('?')?'&':'?')+'_='+Date.now(),timeout:30000,headers:{'Cache-Control':'no-cache'},onload:r=>r.status>=200&&r.status<300?ok(String(r.responseText||'').trim()):no(new Error('HTTP '+r.status)),onerror:()=>no(new Error('网络请求失败')),ontimeout:()=>no(new Error('请求超时'))}));}
  async function latest(){const x=JSON.parse(await get(MANIFEST));const v=String(x.version||'').trim();if(!/^\d+(?:\.\d+){1,3}$/.test(v))throw new Error('远程版本号无效');return{version:v,newer:cmp(v,CURRENT)>0,changelog:Array.isArray(x.changelog)?x.changelog:[],url:String(x.install_url||INSTALL)};}

  function style(){if(document.getElementById('kagura-manual-update-style'))return;const s=document.createElement('style');s.id='kagura-manual-update-style';s.textContent=`.kagura-update-row{display:flex;justify-content:flex-end;align-items:center;gap:6px;margin-top:6px}.kagura-check-update{border:0;border-radius:999px;padding:6px 10px;cursor:pointer;background:#eef4ff;color:#175cd3;font:11px/1.1 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif}.kagura-update-overlay{position:absolute;inset:0;z-index:10000;display:none;align-items:center;justify-content:center;padding:12px;background:rgba(15,23,42,.48)}.kagura-update-overlay.show{display:flex}.kagura-update-modal{width:min(360px,94%);max-height:88%;overflow:auto;background:#fff;color:#182230;border-radius:12px;padding:14px;box-shadow:0 16px 40px rgba(15,23,42,.28);font:13px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif}.kagura-update-title{font-size:16px;font-weight:800;text-align:center;margin-bottom:10px}.kagura-update-result{white-space:pre-wrap;background:#f8fafc;border:1px solid #e4e7ec;border-radius:9px;padding:10px;margin-bottom:10px;max-height:220px;overflow:auto}.kagura-update-actions{display:flex;gap:7px;justify-content:center;flex-wrap:wrap}.kagura-update-actions button{border:0;border-radius:8px;padding:8px 11px;cursor:pointer;font-weight:650}.kagura-update-actions [data-role=check]{background:#e8f7ee;color:#087a3f}.kagura-update-actions [data-role=install]{background:#005bff;color:#fff}.kagura-update-actions [data-role=close]{background:#eef2f6;color:#344054}`;document.documentElement.appendChild(s);}

  function dialog(panel){let o=panel.querySelector(':scope > .kagura-update-overlay');if(!o){o=document.createElement('div');o.className='kagura-update-overlay';o.innerHTML=`<div class="kagura-update-modal"><div class="kagura-update-title">手动检查更新</div><div class="kagura-update-result" data-role="result">当前版本：V${CURRENT}\n\n不会自动检查或自动更新。只有点击“检查更新”时才访问 GitHub。</div><div class="kagura-update-actions"><button type="button" data-role="check">检查更新</button><button type="button" data-role="install" style="display:none">打开更新安装页</button><button type="button" data-role="close">关闭</button></div></div>`;panel.appendChild(o);o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show')});o.querySelector('[data-role=close]').onclick=()=>o.classList.remove('show');o.querySelector('[data-role=check]').onclick=async e=>{const b=e.currentTarget,r=o.querySelector('[data-role=result]'),i=o.querySelector('[data-role=install]');b.disabled=true;b.textContent='检查中…';i.style.display='none';r.textContent=`当前版本：V${CURRENT}\n正在检查 GitHub…`;try{const x=await latest();if(x.newer){const notes=x.changelog.length?'\n\n更新内容：\n'+x.changelog.map((v,n)=>`${n+1}. ${v}`).join('\n'):'';r.textContent=`发现新版本：V${x.version}\n当前版本：V${CURRENT}${notes}\n\n点击“打开更新安装页”，再在 Tampermonkey 页面手动确认。`;i.style.display='';i.onclick=()=>{const a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener noreferrer';document.body.appendChild(a);a.click();a.remove();};}else r.textContent=`当前已经是最新版本：V${CURRENT}`;}catch(err){r.textContent='检查更新失败：'+(err?.message||err);}finally{b.disabled=false;b.textContent='检查更新';}};}o.querySelector('[data-role=result]').textContent=`当前版本：V${CURRENT}\n\n不会自动检查或自动更新。只有点击“检查更新”时才访问 GitHub。`;o.querySelector('[data-role=install]').style.display='none';o.classList.add('show');}

  function patch(panel){if(!panel||panel.dataset.kaguraManualCheck==='1')return;panel.dataset.kaguraManualCheck='1';style();const body=panel.querySelector('.kagura-gpt-body,.kagura-ozon-body')||panel;let v=body.querySelector('[data-role=version],.kagura-gpt-version-btn,.kagura-ozon-version-btn');let row=document.createElement('div');row.className='kagura-update-row';if(v&&v.parentElement){v.parentElement.insertBefore(row,v);row.appendChild(v);}else{v=document.createElement('button');v.type='button';v.textContent='V'+CURRENT;v.style.cssText='border:0;border-radius:999px;background:#0f172a;color:#fff;padding:6px 10px;font:11px/1.1 inherit;cursor:pointer';row.appendChild(v);body.appendChild(row);}const c=document.createElement('button');c.type='button';c.className='kagura-check-update';c.textContent='检查更新';c.onclick=e=>{e.preventDefault();e.stopPropagation();dialog(panel)};row.appendChild(c);}
  const mo=new MutationObserver(()=>document.querySelectorAll('#kagura-gpt-panel,#kagura-ozon-panel').forEach(patch));mo.observe(document.documentElement,{childList:true,subtree:true});document.querySelectorAll('#kagura-gpt-panel,#kagura-ozon-panel').forEach(patch);
})();
